algoritmo "semnome"
// Função :
// Autor :
// Data : 14/05/2022
// Seção de Declarações 
var
   n, soma: real
   cont: inteiro
inicio
      cont<-1
      enquanto (n<>1111) faca
               escreva("Digite o", cont, "° valor:")
               leia(n)
               se (n<>1111) entao
                  soma<-soma+n
                  cont<-cont+1
               fimse
      fimenquanto
      escreva("Soma entre os números digitados:", soma)
// Seção de Comandos 
fimalgoritmo
