algoritmo "semnome"
// Função :
// Autor :
// Data : 07/05/2022
// Seção de Declarações 
var
   N, Cont, S: Inteiro
inicio
      S    <- 0
      Cont <- 1
      Enquanto (Cont<=5) faca
        Escreva("Digite o ", Cont, "° valor ===> ")
        Leia(N)
        S    <- S+N
        Cont <- Cont+1
      FimEnquanto
      Escreva("A soma de todos os valores fornecidos é de ", S)
      
// Seção de Comandos 
fimalgoritmo
