algoritmo "Suidade"
// Função : descobrir as idade do usário a partir do ano atual e de nascimento
// Autor :  thigoo
// Data : 23/02/2022
// Seção de Declarações 
var
    ano_nasc, ano_atual, idade: inteiro
inicio
      Escreva("Informe o ano atual:")
      Leia(ano_atual)
      Escreva("Diga seu ano de nascimento:")
      Leia(ano_nasc)
      idade<- (ano_atual - ano_nasc)
      Escreva("Sua idade é", idade," anos")
// Seção de Comandos 
fimalgoritmo
