algoritmo "semnome"
// Função :
// Autor :
// Data : 24/02/2022
// Seção de Declarações 
var
   N1, N2, Med: Real
inicio
      Escreva("Nota 1: ")
      Leia(N1)
      Escreva("Nota 2: ")
      Leia(N2)
      Med <- (N1 + N2)/2
      Escreval("MÉDIA:", Med)
      Se (Med >= 7) entao
         Escreva("ALUNO APROVADO!")
      senao
         Escreva("ALUNO APROVADO.")
      FimSe
// Seção de Comandos
fimalgoritmo
