algoritmo "semnome"
// Função :
// Autor :
// Data : 17/05/2022
// Seção de Declarações 
var
procedimento gerador(text: caractere)
var c: inteiro
inicio
      escreval("<---------===========--------->")
      para c:=1 ate 4 faca
           escreval("      ", text)
      fimpara
      escreva("<---------===========--------->")
fimprocedimento
inicio
      gerador("Aprendendo Portugol")
// Seção de Comandos 
fimalgoritmo
