algoritmo "semnome"
// Função :
// Autor :
// Data : 24/02/2022
// Seção de Declarações 
var
   Por_d, Anos, Min_P, Dias_P: Real
inicio
      Escreva("Quantos cigarros são fumados por dia?")
      Leia(Por_d)
      Escreva("Quantos anos tem como fumante?")
      Leia(Anos)
      Min_P  <- 365 * Anos * Por_D * 10
      Dias_P <- Min_P/(24*60)
      Escreva("Redução do tempo de vida em dias:", Dias_P)
// Seção de Comandos 
fimalgoritmo
