algoritmo "semnome"
// Função :
// Autor :
// Data : 17/05/2022
// Seção de Declarações 
var
   x, y: inteiro
procedimento soma(var A, B: inteiro)
inicio
             A:=A+1
             B:=B+2
             escreval("Valor de A: ", A)
             escreval("Valor de B: ", B)
             Escreval("Valor de A+B: ", A+B)
fimprocedimento
inicio
      x:=4
      y:=8
      soma(x, y)
      escreval("Valor de x: ", x)
      escreva("Valor de y: ", y)
// Seção de Comandos 
fimalgoritmo
