algoritmo "semnome"
// Função :
// Autor :
// Data : 17/05/2022
// Seção de Declarações 
var
   x, y: inteiro
procedimento somador(A, B: inteiro)
inicio
      escreva("O resultado da soma entre", x, " e", y, " é", A+B, ".")
fimprocedimento
inicio
      escreva("Digite um número: ")
      leia(x)
      escreva("Digite outro número: ")
      leia(y)
      somador(x, y)
// Seção de Comandos 
fimalgoritmo
