algoritmo "semnome"
// Função :
// Autor :
// Data : 23/02/2022
// Seção de Declarações 
var
   L, A, Ar, Litro: Real
inicio
      Escreva("Qual a lagura da parede?")
      Leia(L)
      Escreva("Qual a altura da parede?")
      Leia(A)
      Ar<- A*L
      Litro<- Ar/2
      Escreval("A área a ser pintade é de", Ar, " metros")
      Escreva("Será necessário", Litro, " litros de tinta para pintar a parede")
// Seção de Comandos
fimalgoritmo
