algoritmo "semnome"
// Função :
// Autor :
// Data : 14/05/2022
// Seção de Declarações 
var
   cont,soma, n: inteiro
inicio
      cont:=1
      enquanto (cont<=7) faca
               escreva("Informe o", cont, "° valor:")
               leia(n)
               soma:=soma+n
               cont:=cont+1
      fimenquanto
      escreva("Soma entre os valores:", soma)
// Seção de Comandos 
fimalgoritmo
